// AUTO-GENERATED by scripts/gen-certificates.mjs — do not edit by hand.
// Award keys that have a certificate PDF in public/certificates/.
// Regenerated on every `npm run dev` and `npm run build`.
export const certificateKeys: readonly string[] = [
  "ieee_member",
  "ijtaia_reviewer",
  "scrs_fellow"
];
